name: PMD Code Analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '36 0 * * 1'

jobs:
  pmd-code-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run PMD
        id: pmd # Nadajemy ID, aby móc odwołać się do wyników tego kroku
        uses: pmd/pmd-github-action@967a81f8b657c87f7c3e96b62301cb1a48efef29
        with:
          rulesets: 'rulesets/java/quickstart.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false

      - name: Upload SARIF file
        # Chcemy zawsze przesyłać raport, nawet jeśli build ma zaraz zakończyć się błędem
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif

      # --- NOWY, DODANY KROK ---
      - name: Fail build on PMD violations
        # Ten krok uruchomi się TYLKO WTEDY, gdy liczba błędów z kroku 'pmd' będzie większa od 0
        if: ${{ steps.pmd.outputs.violations_count > 0 }}
        run: |
          echo "PMD found ${{ steps.pmd.outputs.violations_count }} violations, failing the build."
          exit 1
