name: CI with PMD Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run tests
      run: mvn clean test
      
    - name: Run Checkstyle Analysis
      run: mvn checkstyle:check
      continue-on-error: false
      
    - name: Run PMD Analysis
      run: |
        echo "Running PMD analysis..."
        mvn pmd:check || echo "PMD found violations"
        
    - name: Generate PMD Report (always run)
      run: |
        echo "Generating PMD report..."
        mvn pmd:pmd
        
    - name: Check PMD Results
      run: |
        echo "=== PMD Analysis Results ==="
        if [ -f target/pmd.xml ]; then
          echo "PMD XML report generated successfully"
          violations=$(grep -c "<violation" target/pmd.xml 2>/dev/null || echo "0")
          echo "Total violations found: $violations"
          
          if [ "$violations" -gt "0" ]; then
            echo "PMD violations detected:"
            grep -A 3 "<violation" target/pmd.xml | head -20
            exit 1
          else
            echo "No PMD violations found - SUCCESS!"
          fi
        else
          echo "No PMD XML report found"
          exit 1
        fi
        
    - name: Upload PMD Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: pmd-reports
        path: |
          target/site/pmd.html
          target/pmd.xml
          target/site/
